// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-M8Uiok0tIOgdxoWoGk62NgFCnQIVw4w',
    appId: '1:297076893192:web:b85c577af1af8b7b3713bd',
    messagingSenderId: '297076893192',
    projectId: 'weatherapp-2025b',
    authDomain: 'weatherapp-2025b.firebaseapp.com',
    storageBucket: 'weatherapp-2025b.appspot.com',
    measurementId: 'G-PYSZ54FVGZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBiaeY9Eya2K4nX2iTQ7DyhXIRO5aIy2o',
    appId: '1:297076893192:android:dc5d0812951755093713bd',
    messagingSenderId: '297076893192',
    projectId: 'weatherapp-2025b',
    storageBucket: 'weatherapp-2025b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBEW-wFq-YdgJ4wjWinDP_u-yte-OdMy8',
    appId: '1:297076893192:ios:3287d7ebcd1af5533713bd',
    messagingSenderId: '297076893192',
    projectId: 'weatherapp-2025b',
    storageBucket: 'weatherapp-2025b.appspot.com',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBEW-wFq-YdgJ4wjWinDP_u-yte-OdMy8',
    appId: '1:297076893192:ios:3287d7ebcd1af5533713bd',
    messagingSenderId: '297076893192',
    projectId: 'weatherapp-2025b',
    storageBucket: 'weatherapp-2025b.appspot.com',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-M8Uiok0tIOgdxoWoGk62NgFCnQIVw4w',
    appId: '1:297076893192:web:d14682cf181816ff3713bd',
    messagingSenderId: '297076893192',
    projectId: 'weatherapp-2025b',
    authDomain: 'weatherapp-2025b.firebaseapp.com',
    storageBucket: 'weatherapp-2025b.appspot.com',
    measurementId: 'G-BK01VGZYFK',
  );

}